### ISSUE TITLE
Help!

### ISSUE THREAD

**Issue by JPSNYC** [OdedEzer/heebo#10]
Hi there. I recently built a site (in Duda) using Heebo. Everything went completely haywire a couple hours ago.  Attached is a screenshot of a sample paragraph. The problems occur wherever there are commas. Everything after a comma gets completely broken up… Commas appear under letters, and words and characters that follow become misaligned and smushed together. 
 
It appears this may be connected to a recent Heebo update? 

Are you all aware? Do I have any hope this might get fixed? Trying to redesign this site that I just spent about 300 hours working on in recent weeks is a daunting prospect….

Any help/insight would be greatly appreciated. Thank you! 

<img width="692" alt="Sample Heebo problem" src="https://user-images.githubusercontent.com/65315443/81870501-f260d080-9543-11ea-971d-dd61a3725a1e.png">

**Comment by ton-van-alebeek** [comment]
See: https://github.com/google/fonts/issues/2453

**Comment by JPSNYC** [comment]
Thanks https://github.com/ton-van-alebeek for connecting the threads!

**Comment by davelab6** [comment]
This issue can be closed :)

**Comment by JPSNYC** [comment]
Yes, so grateful for the quick response by the team! Many thanks to all.
