### ISSUE TITLE
Glyph Reversed for U+05F1 HEBREW LIGATURE YIDDISH VAV YOD

### ISSUE THREAD

**Issue by markhdavid** [OdedEzer/heebo#6]
Unicode character U+05F1 HEBREW LIGATURE YIDDISH VAV YOD (ױ) (for the combination of letters often called "vov yud" in Yiddish) has images for the component letters mistakenly in reverse order in the glyph: yud then vov (יו) (from right to left); it should be vov then yud (וי)

Here is sample test text: 
  
`- אבגדהוזחטיךכלםמןנסעףפץצקרשת|װ|ױ|ײ|אָ|אַ|בֿ|וּ|יִ|ײַ|כּ|פּ|פֿ|שׂ|תּ
`

It's the Hebrew alphabet plus frequently-used-for-Yiddish Unicode characters and combinations of characters, some with nikudes (diacritics) of various sorts.

Screen shot attached to this report shows font samples taken at the following Google Fonts site: [https://fonts.google.com/specimen/Heebo](https://fonts.google.com/specimen/Heebo)
<img width="1591" alt="Heebo font samples from Google Fonts" src="https://user-images.githubusercontent.com/6209504/56930682-64c65600-6a92-11e9-8daf-0cdb80c89309.png">

Here's a closeup of the bad glyphs:
![vov-yud-closeup](https://user-images.githubusercontent.com/6209504/56931175-fedace00-6a93-11e9-812d-651427972e61.jpg)

**Comment by emmamarichal** [comment]
Hello @meirsadan @OdedEzer,
Following this issue: https://github.com/google/fonts/issues/6602, I took a look to the files.
I've exported the fonts, and run a QA on it, and it seems there are a lot of fails that could be avoided.

I'll probably work on it in the coming weeks, and prepare a bigger upgrade.

**Comment by markhdavid** [comment]
This was fixed no later than commit 76c7d53. It would require some time-consuming research to pinpoint the exact commit, but since I see no point in spending time on that at this point, I'll simply close this issue.
